workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 60
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: master
      cancel_previous_builds: true
    scripts:
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - snikhil280.nk@gmail.com