workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 300
    scripts:
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - snikhil280.nk@gmail.com